### ISSUE TITLE
Add proguard.pro config file and apply it automatically

### ISSUE THREAD

**Issue by xsveda** [yongjhih/proguard-annotations#1]
What about to add [appropriate proguard configuration](https://github.com/facebook/proguard/blob/master/examples/annotations/lib/annotations.pro) and apply it autmatically using library plugins **consumerProguardFiles** property?
I don't see any drawbacks as you can still enable/disable Proguard completely in consumer app.

**Comment by yongjhih** [comment]
Thanks for your suggestion.
